ISSUE - 61 GRIGORIY MIKHEEV
cscenter/practical-minimum-2020-students pull request #26
Opened 2020-09-25 21:20 UTC by Gmihtt

2020-09-25 21:39 UTC, DanielDostanich requested changes

2020-09-25 21:39 UTC, DanielDostanich commented on tasks
> +15 - 38 = 23
THIS IS WRONG

2020-09-25 21:59 UTC, Gmihtt commented on tasks
> +15 - 38 = 23
DONE!!!!!

2020-09-25 21:59 UTC, Gmihtt commented on tasks
> +15 - 38 = 23
FOR GORKA AND MORKA!!!

2020-09-25 22:03 UTC, DanielDostanich approved these changes

2020-09-25 22:48 UTC, Gmihtt commented
Напарник которого я ревьюил
https://github.com/cscenter/practical-minimum-2020-students/pull/28

2020-09-26 08:20 UTC, dehasi commented
@Gmihtt  `Issue-61` -> `ISSUE-61`, `ISSUE - 61` -> ISSUE-61

2020-09-26 08:20 UTC, dehasi approved these changes

2020-09-26 08:23 UTC, dehasi approved these changes

2020-09-26 21:18 UTC, merged