Issue 10 daniel dostanich
cscenter/practical-minimum-2020-students pull request #28
Opened 2020-09-25 22:25 UTC by DanielDostanich

2020-09-25 22:36 UTC, Gmihtt requested changes

2020-09-25 22:36 UTC, Gmihtt commented on tasks
> +40 - 71 = 2
fix pls

2020-09-25 22:40 UTC, DanielDostanich commented on tasks
> +40 - 71 = 2
Fixed the mistake

2020-09-25 22:40 UTC, Gmihtt approved these changes

2020-09-25 22:49 UTC, DanielDostanich commented
Напарник:
https://github.com/cscenter/practical-minimum-2020-students/pull/26

2020-09-26 08:22 UTC, dehasi commented
@DanielDostanich, попросите @Gmihtt  нажать "resolve conversation", если у него нет больше претензий. 
`Issue 10` -> `ISSUE-10`

2020-09-26 08:22 UTC, dehasi approved these changes

2020-09-27 20:17 UTC, dehasi commented
@DanielDostanich  поправьте же заголовок.

2020-09-27 20:19 UTC, dehasi approved these changes

2020-09-27 20:56 UTC, merged