ISSUE-63 Miloserdova Lyubov
cscenter/practical-minimum-2020-students pull request #56
Opened 2020-09-27 13:19 UTC by miloserdova-l

solve task 63 and change line 1

https://my.compscicenter.ru/users/7229/

2020-09-27 14:48 UTC, Demid5 requested changes

2020-09-27 14:48 UTC, Demid5 commented on tasks
> +1 + 60
здесь нужно исправить ошибку

2020-09-27 14:48 UTC, Demid5 commented on tasks
> +85 - 85 = 170
и здесь нужно исправить ошибку

2020-09-27 21:22 UTC, miloserdova-l commented on tasks
> +1 + 60
ошибка исправлена

2020-09-27 21:23 UTC, miloserdova-l commented on tasks
> +85 - 85 = 170
ошибка исправлена

2020-09-28 05:46 UTC, Demid5 approved these changes

2020-09-28 11:15 UTC, dehasi approved these changes

2020-09-28 12:56 UTC, merged