ISSUE-37 Kutuev Timur
cscenter/practical-minimum-2020-students pull request #74
Opened 2020-09-27 21:50 UTC by timur9831

1) Correct solve task
2) Solve a task not correct
3) Change one number in task

2020-09-27 22:02 UTC, Timur418 reviewed
Seems that it's not correct

2020-09-27 22:03 UTC, Timur418 commented
Seems that you have some mistake!

2020-09-27 22:06 UTC, timur9831 commented
# @Timur418 Fix bug. Unfortunately, if was ficha.

2020-09-27 22:09 UTC, Timur418 requested changes

2020-09-27 22:09 UTC, Timur418 commented on tasks
> +73 - 45 = 25
Not correct

2020-09-27 22:09 UTC, timur9831 commented on tasks
> +73 - 45 = 25
Got it before.

2020-09-27 22:13 UTC, timur9831 commented
Напарник ушел на боковую, пришлось делать с двух аккаунтов :(

2020-09-28 07:24 UTC, dehasi commented
Общаться с самим собой это, конечно, хорошо. Но всегда лучше, когда ваши изменения смотрит другой человек.

2020-09-28 07:24 UTC, dehasi approved these changes

2020-10-04 10:45 UTC, merged