ISSUE-INFTY Ilya MIkhaylov
cscenter/practical-minimum-2020-students pull request #78
Opened 2020-09-27 22:51 UTC by IlyaMikhaylovTim

Solved first problem two times, also solved one more problem (fourth or third, don't remember exactly).

https://my.compscicenter.ru/users/5622/

2020-09-28 07:44 UTC, lo0op requested changes

2020-09-28 07:44 UTC, lo0op commented on tasks
> +71 + 11 = 94
incorrect answer here

2020-09-28 08:50 UTC, IlyaMikhaylovTim commented on tasks
> +71 + 11 = 94
Поправил, чекай.

2020-09-28 09:00 UTC, lo0op approved these changes

2020-09-28 09:52 UTC, dehasi commented
@IlyaMikhaylovTim `ISSUE-INFTY` -> `ISSUE-76`

2020-09-28 09:52 UTC, dehasi approved these changes

2020-09-29 12:17 UTC, dehasi commented
@IlyaMikhaylovTim  Номер тикета в коммитах поправьте пожалуйста.

2020-09-29 12:17 UTC, dehasi approved these changes

2020-09-29 14:36 UTC, merged